### PR TITLE
Support for 'less than' thresholds

### PR DESCRIPTION
**Pull request by flingo64**
Added support for 'less than' warning/critical thresholds (expressed by a trailing colon).
Example:
  check_powerdns_dist.py .... -w 2000 -c 10: 
This will generate a warning if more than 2000 req/s received, but also a critical if less than 10 req/s were received.

### CODE REVIEW

**Comment by rfrenayworldstream** [comment]
Hi, I really like your idea, I think it will add value to the plugin.
In your pull request the threshold is either a minimum or maximum value. I think it would more complete if we allow both a minimum and maximum boundary at the same. The format of the threshold can be according the specification defined in this link https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

**Comment by flingo64** [comment]
It's definitely a very limited imlementation of the Nagios threshold syntax, but it's better than nothing and it solved my problem. :-)
A complete implementation of the Nagios threshold syntax would be a good idea, but might get complex. There is a [NagiosPlugin python class](https://github.com/mpounsett/nagiosplugin) doing the complete threshold syntax, but I don't like the idea of requiring another pip package for the plugin.
So, I would suggest this patch as a first step and see if I could find some valid code for the whole syntax parsing.

**Comment by rfrenayworldstream** [comment]
I also prefer a solution without using the NagiosPlugin class. If you want I can help you with a function for the threshold checking. The following week I'm very busy, but in week 51 I can make time to do this.

**Comment by flingo64** [comment]
Sounds good! I check if I can find some code dealing with Nagios thresholds (I found some perl code doing this, porting to py shouldn't be too hard). 
Anyway: any plans to combine check_powerdns_auth.py and check_powerdns_dist.py? Most of the code is identical. In fact, I started with  check_powerdns_auth.py and added dnsdist support, just to realize after all, that there is already check_powerdns_dist.py available (if I just had googled 2 seconds longer ... ;-))

**Comment by rfrenayworldstream** [comment]
Please let me know what you think of the function below. I based the code on the nagiosplugin, but this one only support positive integers.
It returns True if an alert should be generated.

```
    # Function is based on /nagiosplugin/range.py in https://github.com/mpounsett/nagiosplugin/
    def threshold_alert(self, _value, _spec):
        invert = False

        try:
            if _spec.startswith('@'):
                invert = True
                _spec = _spec[1:]
            if ':' in _spec:
                start, end = _spec.split(':')
            else:
                start, end = '', _spec
            if start == '~' or start == '':
                start = 0
            else:
                start = int(start)
            if end == '':
                end = None
            else:
                end = int(end)
        except ValueError:
            raise MyThresholdError("Invalid Threshold format")

        if (end is not None) and (start > end):
            raise MyThresholdError("Threshold start should be less or equal to end")

        if _value < start:
            return True ^ invert
        if (end is not None) and (_value > end):
            return True ^ invert
        return False ^ invert
```

**Comment by flingo64** [comment]
Works great if value ist of type integer.

Perfect!

**Pull request merged**
